# Generated by Django 2.2.4 on 2023-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShows_app', '0002_auto_20230606_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='network',
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
