# Generated by Django 2.2.4 on 2023-06-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='old author'),
            preserve_default=False,
        ),
    ]
